### ISSUE TITLE
Changing the actual grid aesthetic

### ISSUE THREAD

**Issue by AHazy** [cs361fall2018/project-team-22#20]
Change the basic black and white grid to a more appealing board.  Make it mostly blue (for water) and have images for hit and miss such as fire and splashes.  Make the grid lines less intense.

**Comment by AdamTogether** [comment]
- Squares on grid should be blue by default.
- Grid lines grey, or off-blue.
- Add animation for hit and miss.

**Comment by AdamTogether** [comment]
- Added flame emoji for hit.
- Added water droplet emoji for miss.
- Changed grid lines from black to gray.
- Changed the board's background to lightskyblue.
