### ISSUE TITLE
Allow user to input name for the grids

### ISSUE THREAD

**Issue by AHazy** [cs361fall2018/project-team-22#21]
Have the game start with default names for the two grids (such as Allies vs Enemies).  Allow the user to change both of these names.  Implement the names in the attack log

**Comment by mertdedekoy** [comment]
Text boxes are added for entering player and enemy's name. But it needs to more design.

**Comment by AHazy** [comment]
The ability to input grid names is now on master branch.  However, @mertdedekoy please style it better with CSS.
